FROM node:alpine

RUN apk update && apk add python3.8 make g++

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node ./package*.json ./
#COPY ./package*.json ./

RUN npm i 

COPY --chown=node:node . . 
#COPY . . 

CMD ["npm","start"]