version: "3"
services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
    redis:
        image: redis:latest

        #we custimized default nginx image and will use it
    nginx:
        depends_on:
            - api
            - client
        #if something happens,always restart
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - "3000:80" #my_port:container_port

    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./frontend
        volumes:
            - /app/node_modules #ignore this file and don't watch it
            - ./frontend:/app
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./backend
        volumes:
            - /app/node_modules
            - ./backend:/app
