version: "3"
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        hostname: mongodb
        volumes:
            - ./.docker/mongodb/mongod.conf:/etc/mongod.conf
            - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
            - ./.docker/mongodb/data/db/:/data/db/
            - ./.docker/mongodb/data/log/:/var/log/mongodb/
        env_file:
            - .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        ports:
            - "27017:27017"
        command: ["-f", "/etc/mongod.conf"]
    redis:
        image: redis:latest

        #we custimized default nginx image and will use it
    nginx:
        depends_on:
            - api
            - client
        #if something happens,always restart
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - "3000:80" #my_port:container_port

    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./frontend
        volumes:
            - /home/node/app/node_modules #ignore this file and don't watch it
            - ./frontend:/home/node/app
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./backend
        volumes:
            - /home/node/app/node_modules
            - ./backend:/home/node/app
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_ROOT_USERNAME}
            MONGODB_URI: ${MONGODB_URI}
            REDIRECT_URL: ${MONGO_INITDB_ROOT_USERNAME}
            CLOUDINARY_CLOUD_NAME: ${MONGO_INITDB_ROOT_USERNAME}
            CLOUDINARY_API_KEY: ${MONGO_INITDB_ROOT_USERNAME}
            CLOUDINARY_API_SECRET: ${MONGO_INITDB_ROOT_USERNAME}
            JWT_SECRET: ${MONGO_INITDB_ROOT_USERNAME}
            JWT__REFRESH_SECRET: ${MONGO_INITDB_ROOT_USERNAME}
            GOOGLE_API_KEY: ${MONGO_INITDB_ROOT_USERNAME}
            GOOGLE_API_SECRET: ${MONGO_INITDB_ROOT_USERNAME}
            FACEBOOK_API_KEY: ${MONGO_INITDB_ROOT_USERNAME}
            FACEBOOK_API_SECRET: ${MONGO_INITDB_ROOT_USERNAME}
            OAUTH_GOOGLE_REDIRECT: ${MONGO_INITDB_ROOT_USERNAME}
            OAUTH_FACEBOOK_REDIRECT: ${MONGO_INITDB_ROOT_USERNAME}
